name: "EAS Update"
description: ""
inputs:
  branch-name:
    description: 'The name of the pull request branch, use github.head_ref || github.ref_name'
    required: true
  github-token:
    description: 'The GitHub token for the user that should post pull request comments.'
    required: true
  github-username:
    description: 'The GitHub username of the user who owns the PAT'
    required: true
  organization-name:
    description: 'The name of the owner on GitHub'
    required: true
  repository-name:
    description: 'The name of the repository'
    required: true
  update-url:
    description: 'The Expo update URL of the application/project'
    required: false
runs:
  using: "node16"
  main: "../../dist/actions/expo/update.js"
